#!/usr/bin/env bash 
#if [ "$(id -un)" != "root" ]; then echo "Need root - sudoing..."; exec sudo "$0" "$@" fi

ARG1=$1
ARG2=$2
ARG3=$3
DISPLAYS=($(ddcutil detect | grep Display | awk '{print $2}'))
MOD=""; if [[ $ARG2 = "up" ]]; then MOD="+"; else MOD="-"; fi

br() {
  for (( i=0; i<${#DISPLAYS[@]}; i++ )); do
    ddcutil -d ${DISPLAYS[$i]} setvcp 10 $1 $2
  done
}

br_get() {  br=$(ddcutil -d 2 getvcp 10 | awk '{print substr($9, 1, length($9)-1)}') }
br_set() {  br $MOD $ARG3;  }
br_max() {  br 100;         }
br_min() {  br 10;          }
br_mid() {  br 50;          }
br_error() {
      printf "\v      "
      printf "Invalid Argument"
      printf "\v\n      "
      printf "Valid Arguments are 'up', 'down', 'max', 'min', 'mid' " \n
      printf "\v\n      "
      printf "Example: # <script.sh> up"
      printf "\n\v"
}

case $ARG1 in
  get)    br_get; echo $br  ;;
  set)    br_set    ;;
  max)    br_max    ;;
  min)    br_min    ;;
  mid)    br_mid    ;;
  *)      br_error  ;;
esac
  

#  echo $IFS > `tty`
#  echo "arg1: $ARG1" > `tty`
#  echo "arg2: $ARG2"
#  echo "arg3: $ARG3"
#  echo "displays: ${DISPLAYS[@]}"
#  echo "displaylength: ${#DISPLAYS[@]}"
